name: flutter_localization
description: Flutter Localization
version: 0.0.8
author: Filip Rajicic
homepage: www.credeo.de

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  kiwi: ^2.0.0
  http: ^0.12.2
  path_provider: ^1.6.14
  devicelocale: ^0.3.1
  graphql_flutter: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: