name: flutter_localization
description: Flutter Localization
version: 2.0.0
author: Filip Rajicic
homepage: www.credeo.de

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  devicelocale: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: